### ISSUE TITLE
explanation of references that appear as solely an icon of a camera

### ISSUE THREAD

**Issue by mtholder** [rdmpage/bionames#22]
For example every page of http://bionames.org/references/a8c3a1d1a75731eb4586d65991a30aab

I'm not sure what is going on with this article. Are there some steps that a user can take to track down the source of the problem?

(Thanks for bionames, btw. I've gotten a lot of use out of it recently)

**Comment by mtholder** [comment]
looks like it is no longer avaiable in BHL. See http://www.biodiversitylibrary.org/itemunavailable

... and don't bother to point out the irony of the fact that I'm at KU looking for this publication of the "Kansas University Science Bulletin" - I'm aware of it. ;-)

**Comment by rdmpage** [comment]
Hi @mtholder glad you're finding BioNames useful. As you've figured out, BHL has deleted the pages corresponding to the article. Occasionally BHL deletes a scanned volume and replaces it with a new one, changing the PageIDs in the process (sigh). I've located the new version and fixed BioStor http://biostor.org/reference/98372 and BioNames http://bionames.org/references/a8c3a1d1a75731eb4586d65991a30aab
