### ISSUE TITLE
Metadata for non-Hindawi Psyche articles

### ISSUE THREAD

**Issue by jar398** [rdmpage/bionames#27]
The Hindawi scans (and the Hindawi DOIs) of Psyche cover about 95% of the corpus. I've prepared a CSV file that gives metadata for about 250 additional papers, ones that were not available to Hindawi when they scanned, but that are all available in BHL.

Notes on format
- see header row for column meaning
- there is some HTML markup, `<i>` for italic and `&eaigu;` and so on for special characters
- authors are separated by semicolon (but do not treat semicolon as a separator in the title column)

I tried to attach the file to this issue, but github keeps saying "something went really wrong and we can't process that file".  I've placed it here for you to pick up:

http://mumble.net/~jar/tmp/psyche-metadata-for-bionames.csv

**Comment by rdmpage** [comment]
@jar398 I Jonathan, I've moved this to BioStor (apologies for the confusing Bio* names). Many thanks for the metadata.

**Comment by jar398** [comment]
moved to https://github.com/rdmpage/biostor/issues/65.

(duh, I knew the difference between the projects, just didn't think)
